# Generated by Django 5.0.4 on 2024-04-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('changelog', models.TextField(verbose_name='Changelog')),
                ('datetime', models.DateTimeField(verbose_name='Date/Time')),
            ],
        ),
    ]
